<?php
require_once '../wp-blog-header.php';

$nameArray = array(
    "Alba Vásquez Jiménez",
    "Alberto Díaz Araya",
    "Aldo Vidal Herrera",
    "Alejandra  Lunecke Reyes",
    "Alejandra Araya Espinoza",
    "Alejandra Brito Peña",
    "Alejandra Castillo",
    "Alejandra Falabella",
    "Alejandra González Celis",
    "Alejandra Ruiz Tarrés",
    "Alejandra Vega Palma",
    "Alejandra Vidal Elgueta",
    "Alejandra Villarroel Peña",
    "Alejandro Carrasco",
    "Alejandro Garcés",
    "Alejandro Reinoso",
    "Alejandro Tudela",
    "Alessandro Santoni",
    "Alex Ibarra Peña",
    "Alexis Cortes Morales",
    "Alexis Rebolledo Carreño",
    "Alfonso Donoso",
    "Alfredo Irribarra Amarales",
    "Alfredo Joignant",
    "Alicia Foxley Valdivieso",
    "Álvaro Bello M.",
    "Álvaro Elgueta Horn",
    "Álvaro García San Martín",
    "Álvaro Jiménez Molina",
    "Álvaro Sandoval Fedelli",
    "Álvaro  Soto  Roy",
    "Amari Peliowski Dobbs",
    "Ana  Carolina Rodríguez",
    "Ana María Alarcón",
    "Ana María Baeza C.",
    "Ana María Ledezma S.",
    "Ana María Risco",
    "Ana Pizarro",
    "Ana Vergara del Solar",
    "André Menard",
    "Andrea Giovanna Ronconi Vergara",
    "Andrea Helo",
    "Andrea Lira Muñoz",
    "Andrea Peroni",
    "Andrea Roberta Kottow Keim",
    "Andrea Ruffinelli",
    "Andrea Seelenfreund",
    "Andrea Valdivia Barrios",
    "Andrea Vera Gajardo",
    "Andrés Estefane",
    "Andres Haye",
    "Andrés Rojas Verdugo",
    "Ángeles Donoso Macaya",
    "Antonia Lara",
    "Antonia Larraín Sutil",
    "Antonio Morello Caste",
    "Antonio Rivera Hutinel",
    "Antonio Stecher",
    "Ariadna Biotti",
    "Arone-Ru Gumas López",
    "Asmara Ramírez Giannini",
    "Aurora Ruiz Mendoza",
    "Azun Candina Polomer",
    "Baldomero Estrada Turra",
    "Bedrich Magas Kusak",
    "Belén Valdés Velasco",
    "Beltrán Undurraga",
    "Bernardo Subercaseaux S.",
    "Bernardo Valdés Echenique",
    "Camila Camacho Ulloa",
    "Camila Gatica Mizala",
    "Camila León Gin",
    "Camila Moyano Dávila",
    "Camilo A",
    "Carla Moscoso Rojas",
    "Carla Muñoz Valenzuela",
    "Carla Rivera A.",
    "Carlos Carrasco González",
    "Carlos Contreras Guala",
    "Carlos Daniel Uribe Álvarez",
    "Carlos del Valle Rojas",
    "Carlos Donoso Rojas",
    "Carlos González Lagos",
    "Carmen Gloria Fuentealba Pérez",
    "Carmen Gloria Hidalgo Carmona",
    "Carmen Gloria Ruiz Bustamante",
    "Carol Lindy Joglar Campos",
    "Carola Flores",
    "Carola Otth Lagunas",
    "Carole Sinclaire Aguirre",
    "Carolina Beatriz Franch Maggiolo",
    "Carolina Belmar",
    "Carolina Brito Chávez",
    "Carolina Casanueva",
    "Carolina Flores",
    "Carolina Garrido Silva",
    "Carolina González Undurraga",
    "Carolina Guerta",
    "Carolina Guzmán Valenzuela",
    "Carolina Mateluna Astorga",
    "Carolina Muñoz Amigo",
    "Carolina Rojas Lasch",
    "Carolina Sepúlveda Serani",
    "Carolina Stefoni",
    "Caroline Ruth Weinstein Oppenheimer",
    "Catalina Amigo Jorquera",
    "Catalina Arteaga A.",
    "Catalina Valdés Echenique",
    "Cathereen Coltters Illescas",
    "Cecilia Osorio",
    "Cecilia Sánchez",
    "César A",
    "César González Moris",
    "César Ladrón de Guevara",
    "Cherie Zalaquett Aquea",
    "Christian Augusto Larotonda Dinardi",
    "Cindy Thraves Caro",
    "Claudia Alejandra  Eterovic Díaz",
    "Claudia Andrea Estrada Goic",
    "Claudia Andrea Silva Díaz",
    "Claudia Calquín Donoso",
    "Claudia Fedora Rojas Mira",
    "Claudia Gabriela Cameratti Baeza",
    "Claudia Gutiérrez Villegas",
    "Claudia Lorena Riquelme Macalusso",
    "Claudia Matus Cánovas",
    "Claudio Contreras Carvajal",
    "Claudio Fuentes Saavedra",
    "Claudio Guerrero Valenzuela",
    "Claudio H",
    "Claudio Ramos Zincke",
    "Colombina Schaeffer",
    "Constanza Terra Polanco",
    "Constanza Vergara",
    "Consuelo Huidobro Marín",
    "Cristian Becker Álvarez",
    "Cristian Esteban Serey Gaggero",
    "Cristián Frêne Conget",
    "Cristian Solar Valenzuela",
    "Cristina Moyano",
    "Cristina Quezada Rodríguez",
    "Cristóbal Balbontín Gallo",
    "Cristóbal Bianchi Geisse",
    "Cristóbal Enrique Vallejos Fabres",
    "Cristóbal Friz Echeverría",
    "Cristóbal Kauak",
    "Cristóbal Villalobos Dintrans",
    "Dagmar Raczynski",
    "Daniel Cano Christiny",
    "Daniel Pavlovic",
    "Daniel Valenzuela Galarce",
    "Daniela Maira Moya",
    "Daniela Olivares Aising",
    "Daniela Serra",
    "Danilo Sanhueza O.",
    "David González Padilla",
    "Debbie E",
    "Denis Chevallay",
    "Diana Pasmanik",
    "Diego Partarrieu Bravo",
    "Dora Muñoz Contreras",
    "Eduardo Carrasco H.",
    "Eduardo Fermandois M.",
    "Eduardo Montecinos Fierro",
    "Eduardo Valenzuela Avaca",
    "Eliana Chamizo",
    "Eliana Verónica Hidalgo Fuentes",
    "Elizabeth Collingwood-Selby",
    "Elizabeth Jorquera Pizarro",
    "Elvira López Taverne",
    "Emilio René Alejo Rivas Faure",
    "Emma de Ramón",
    "Emmanuelle Barozet",
    "Enrique Fernández Darraz",
    "Ericka Natalia Portilla Barrios",
    "Ernesto Andrés Teneb Barrientos",
    "Esteban Radiszcz S.",
    "Estefanía Paz Hermosilla Ordenes",
    "Eva Cancino Fuentes",
    "Fabiana María Martin",
    "Felipe Burrows",
    "Felipe Camerati",
    "Felipe Cussen",
    "Felipe Esteban Bravo Peña",
    "Felipe Ghiardo",
    "Felipe Godoy Ossa",
    "Felipe Mallea Toledo",
    "Felipe Orellana Gallardo",
    "Felipe Ossio",
    "Felipe Osvaldo Zúñiga Verdugo",
    "Felipe Parra Galaz",
    "Felipe Ubeira Osses",
    "Felipe Valdivieso L.",
    "Fernanda Poblete",
    "Fernanda Salinas",
    "Fernanda Soler Urzúa",
    "Fernando Estenssoro",
    "Fernando Javier Muñoz León",
    "Fernando Maureira Tapia",
    "Fernando Ormeño U.",
    "Fernando Ossandón Correa",
    "Fernando Pérez Villalón",
    "Fernando Valenzuela Arteaga",
    "Fiorella Zecchetto Arata",
    "Flavia Morello Repetto",
    "Florencia Gómez Zaccarelli",
    "Florencia Henríquez",
    "Florencia Muñoz Ebensperger",
    "Francis William Mason Bustos",
    "Francisca Avilés",
    "Francisca Katz Galaz",
    "Francisca Márquez",
    "Francisco Jeanneret B.",
    "Francisco Manuel Mujica Coopman",
    "Francisco Ojeda Sánchez",
    "Francisco Pereira Gandarillas",
    "Gabriel Emiliano Urzúa Vera",
    "Gabriela Carmona Sciaraffia",
    "Gabriela Cruz",
    "Gabriela Diéguez Santa María",
    "Gabriela González Vivanco",
    "Gabriela Iglesias Letelier",
    "Gabriela Toledo",
    "Gabriela Toro Arriagada",
    "Gaspar Pujadas Tafra",
    "Gastón Biotti Flores",
    "Genoveva Echeverría",
    "Gerardo Mora Rivera",
    "Gerardo Muñoz Troncoso",
    "Gerardo Zúñiga Navarro",
    "Giancarlo Urzua",
    "Gina  Mancilla Saavedra",
    "Gisella Morety Robles",
    "Gladys Astete Cereceda",
    "Gloria Baigorrotegui",
    "Gloria Cortés Aliaga",
    "Gonzalo Andrés Salazar",
    "Gonzalo  Arqueros",
    "Gonzalo Muñoz",
    "Gonzalo Núñez Erices",
    "Gonzalo Pimentel Guzmán",
    "Gonzalo Saavedra Gallo",
    "Gonzalo Zapata",
    "Gregorio Fernando Calvo García",
    "Grinor Rojo",
    "Guillermo Molina Holmes",
    "Guillermo Muñoz Contreras",
    "Guillermo Williamson Castro",
    "Gustavo Cataldo Sanguinetti",
    "Hans Gundermann K.",
    "Haydée Vivar Cid",
    "Héctor Cabezas Correa",
    "Héctor González Cortez",
    "Helena Horta Tricallotis",
    "Heriberto Fernández Jaramillo",
    "Herminio Sandoval Borquez",
    "Hilda Ruby Vizcarra Rebolledo",
    "Hugo Contreras Cruces",
    "Hugo Rojas Corral",
    "Ignacio Agüero",
    "Ignacio Castillo",
    "Ignacio López Escarcena",
    "Ignacio Marchant Bouffanais",
    "Ignacio Ramos Rodillo",
    "Ignacio Voullieme Bruñol",
    "Ignacio Zenteno Sotomayor",
    "Inés Figueroa",
    "Irma Arriagada",
    "Isaac Caro",
    "Isabel Llona",
    "Isidora Gilardi",
    "Isis Fuentes Pereira",
    "Iván Grudechut",
    "Ivonne Vargas",
    "Jaime Valenzuela Márquez",
    "Javier Rodríguez Morales",
    "Javiera Roa Infante",
    "Jimena Celeste Reyes Guzmán",
    "John Charney",
    "Jorge Agustín Rosales Salas",
    "Jorge Alberto Martin Bascuñán",
    "Jorge Hernández Cerda",
    "Jorge Iván Vergara del Solar",
    "Jorge Lillo R.",
    "Jorge Mittelmann",
    "Jorge Rodrigo Lorca Leiva",
    "Jorge Valenzuela Carreño",
    "Jorge Vera Buschmann",
    "Jorge Vera Roda",
    "José Alberto de la Fuente Arancibia",
    "José Antonio Román Brugnoli",
    "José  Berenguer Rodríguez",
    "José Cornejo Abarca",
    "José Francisco Blanco Jara",
    "José Jara",
    "José Luis Cáceres Fernández",
    "José Manuel Ferreiro",
    "José Manuel Melero",
    "José Miguel Palacios",
    "José Miguel Quintana Espinoza",
    "José Venturelli Barón",
    "Josefina González Andreu",
    "Josué Pino Castillo",
    "Juan Antonio Ormeño Karzulovic",
    "Juan Carlos Skewes Vodanovic",
    "Juan Enrique García Gutiérrez",
    "Juan  Espinoza Hormazábal",
    "Juan Felipe Espinosa Cristia",
    "Juan Ignacio Marambio Morel",
    "Juan Joaquín Aedo Alvarado",
    "Juan José Adriasola",
    "Juan José Ayarza P.",
    "Juan José Richards Echeverría",
    "Juan Luis García",
    "Juan Pablo Venables Brito",
    "Judith Reyes García",
    "Justino Gómez de Benito",
    "Karen Carla Rosenfeld Ytier",
    "Karen Pérez de Arce Guzmán",
    "Karina Vargas Barria",
    "Karla Henríquez Ojeda",
    "Katherine Alvear",
    "Katherine Medina Pino",
    "Kevin Villegas",
    "Leonardo Aliaga Rovira",
    "Leonardo Valenzuela",
    "Leonora Díaz Moreno",
    "Liliana Coltters Illescas",
    "Liliana Manzano",
    "Lilith Kraushaar H.",
    "Lissett Valenzuela",
    "Lorena Amaro Castro",
    "Lorena Francisca Berrios Barra",
    "Loreto Margarita Valenzuela Roediger",
    "Lucía Stecher",
    "Luis Alberto Paiva M.",
    "Luis Castro",
    "Luis Emilio Rojas Aguirre",
    "Luis Guasch Guzmán",
    "Luis Guzmán Palacios",
    "Luis Henríquez Riutor",
    "Luis Placencia",
    "Luis San Martín Arzola",
    "Luis San Martín Mena",
    "Luis Thielemann H.",
    "Luis Villavicencio Miranda",
    "Lynda Eulogia Avendaño Santana",
    "Macarena Bonhomme",
    "Macarena Cordero Fernández",
    "Macarena Isabel Ahumada Maceratta",
    "Macarena Mallea",
    "Mafalda Abarca Volante",
    "Magdalena Gil Ureta",
    "Magdalena Guerrero",
    "Magdalena Pardo",
    "Maira Mora González",
    "Maite de Cea",
    "Maite Paulina Salazar Lopéz",
    "Manuel Alejandro Orbenes Cuellar",
    "Manuel Antonio Garretón",
    "Manuel Prieto Estades",
    "Manuel San Román Bontes",
    "Manuel Tironi",
    "Manuel Torres Sahli",
    "Manuel Uribe Rivera",
    "Manuela Abud Novoa",
    "Marc Zeise",
    "Marcela Cubillos Poblete",
    "Marcela Denis Castro Garrido",
    "Marcela Inzunza Díaz",
    "Marcela Labraña",
    "Marcela Lobo Bustamante",
    "Marcela Rivera",
    "Marcela Verónica Apablaza Santis",
    "Marcelo Berho",
    "Marcelo Casals Araya",
    "Marcelo Mayorga Zúñiga",
    "Marco Antonio Villalta Paucar",
    "Marco Berland O.",
    "Marcos Aguirre",
    "Margarita Alvarado Pérez",
    "Margarita Garrido Espinoza",
    "Margarita Iglesias Saldaña",
    "María Andrea Ponce Laval",
    "María Ángela Lertora López",
    "María Ángela Peñaloza",
    "María Angélica Oliva Ureta",
    "María Angélica Sotomayor Saavedra",
    "María Catalina Sime Zegarra",
    "María Elena Fuentes Alarcón",
    "Maria Eugenia Albornoz Vasquez",
    "María Eugenia Góngora",
    "María Eugenia Solari Alberti",
    "María Francisca Fernández Donoso",
    "María Gabriela Rubilar Donoso",
    "María Isabel du Monceau de Bergendal",
    "María Isabel Pardo Vallejos",
    "María Isabel Toledo Jofré",
    "María Jesús Inostroza",
    "María José Azocar",
    "María José Contreras",
    "María José Herrera Soto",
    "María José Muñoz León",
    "María José Muñoz",
    "María José Reyes Andreani",
    "María José Yaksic",
    "María Josefina Escobar",
    "María Josefina Schenke Reyes",
    "María Loreto Rebolledo G.",
    "María Magdalena García Barra",
    "María Paulina Soto Labbé",
    "María Paz Peña Lagos",
    "María Paz Trebilcock",
    "María Paz Undurraga Riesco",
    "María Rosa Lissi",
    "María Rosario Cordero Fernández",
    "María Soledad Jiménez  Morales",
    "María Teresa Santander Gana",
    "María Victoria Castro",
    "María Victoria Soto Bäuerle",
    "María Ximena Urbina Carrasco",
    "Mariana Vargas Orellana",
    "Marianela Denegri Coria",
    "Marianne Daher Gray",
    "Mario A",
    "Mario Ociel Moya",
    "Mario Quintanilla Gatica",
    "Marjorie Murray",
    "Marlene Arismendi Macuer",
    "Marta Alfonso Durruty",
    "Marta Silva Fernández",
    "Martín Correa Cabrera",
    "Martín Tironi",
    "Mary Jane Abrahams",
    "Matías Fernández Hernández",
    "Mauricio Arteaga M.",
    "Mauricio Miraglia",
    "Mauricio Rojas Alcayaga",
    "Mauro Basaure",
    "Maximiliano Michell",
    "Maximiliano Zagal",
    "Miguel Valderrama",
    "Mike van Treek  Nilsson",
    "Mireya Palavecinos Tapia",
    "Mónica Acuña Patzke",
    "Mónica Peña Ochoa",
    "Nadia Silhi Chahin",
    "Nanette Liberona Concha",
    "Nanette Vergara Aguilera",
    "Natalia Ávila",
    "Natalia Martínez Barrios",
    "Natalia Miranda Calderón",
    "Natalia Möller González",
    "Natalia Pessa Gutiérrez",
    "Natalia V",
    "Natalia Vargas Márquez",
    "Nataniel Izquierdo Leiva",
    "Nelson Valenzuela Valenzuela",
    "Néstor Lagos",
    "Nicolás Crisóstomo Fernández",
    "Nicolás Libedinsky",
    "Nicolás Ocaranza",
    "Nury González",
    "Olga Espinoza",
    "Olga Grau Duhart",
    "Olga Ulianova",
    "Omar Rodrigo Reyes Báez",
    "Omar Turra Díaz",
    "Oscar Aguilera Ruiz",
    "Oscar Ariel Cabezas",
    "Oscar Salvador Toro Bardeci",
    "Osvaldo Carvajal Muñoz",
    "Pablo Berríos González",
    "Pablo Brugnoli",
    "Pablo Cabrera Pérez",
    "Pablo Cesar Olivos Jara",
    "Pablo Chiuminatto",
    "Pablo Cuevas Valdés",
    "Pablo Ismael Enrique Concha Ferreccio",
    "Pablo Langlois Prado",
    "Pablo Lobos Ruiz",
    "Pablo Méndez-Quirós Aranda",
    "Pablo Olguín Veloso",
    "Pablo Oyarzun Robles",
    "Pablo Rupin Gutiérrez",
    "Pablo Venegas Cancino",
    "Pamela Ramírez",
    "Paola Bolados García",
    "Paola Díaz",
    "Paola Lagos Labbé",
    "Paola Paredes Suzarte",
    "Patricia Castillo Gallardo",
    "Patricia Moya Cañas",
    "Patricio Alejandro Urrutia González",
    "Paula de la Fuente Stranger",
    "Paula Orta Camus",
    "Paula Soledad Viano Santana",
    "Paulette Faure",
    "Paulina Pizarro",
    "Paulo Moya Riquelme",
    "Pedro Cid-Agüero",
    "Pía Uribe",
    "Pilar Isabel Rivas Cardemil",
    "Rafael Gaune Corradi",
    "Rafael Ruiz Moscatelli",
    "Rafaella Canessa Mesías",
    "Ramiro González Rial",
    "Raquel Aguilera Insunza",
    "Raúl Molina Otarola",
    "Raúl Rodríguez Freire",
    "Rayen Ximena Navarro Harris",
    "Reinaldo Rioseco Hormazábal",
    "Renato Joaquín Moretti Tapia",
    "Ricardo De Pol Holz",
    "Ricardo Ferrada Alarcón",
    "Ricardo Greene",
    "Roberto Aceituno Morales",
    "Rodolfo Hermans",
    "Rodrigo Antonio Rojas Hernández",
    "Rodrigo Bilbao Ramírez",
    "Rodrigo Cánovas Emhart",
    "Rodrigo Eduardo Retamal Yermani",
    "Rodrigo González Holgado",
    "Rodrigo Karmy Bolton",
    "Rodrigo Marcelo Céspedes Sotomayor",
    "Rodrigo Salcedo",
    "Rodrigo Sánchez Romero",
    "Rodrigo Uribe Bravo",
    "Rodrigo Zúñiga C.",
    "Rolando Rebolledo Berroeta",
    "Ronald Cancino Salas",
    "Rosa Gaete Moscoso",
    "Rosanna Forray Claps",
    "Rosario Undurraga Riesco",
    "Rubén Eugenio Orellana Ahumada",
    "Ruby Vizcarra Rebolledo",
    "Ruth Kries Saavedra",
    "Sabina García Peter",
    "Sandra Herrera Alcayaga",
    "Sandra Leiva",
    "Sebastián G",
    "Sebastián Ignacio  Cepeda Haro",
    "Sebastián Ignacio Ibarra González",
    "Sebastián Kaufmann",
    "Sebastián Ureta Icaza",
    "Sebastián Venegas Rojo",
    "Sergio Cornejo Erices",
    "Sergio González Rodríguez",
    "Sergio Grez Toso",
    "Sergio Martínez V.",
    "Sergio Palma M.",
    "Sergio Rojas Contreras",
    "Silvia Lamadrid Álvarez",
    "Silvia Paillán Campos",
    "Silvia Quevedo Kawasaki",
    "Simón Escoffier",
    "Simón Palominos Mandiola",
    "Simón Smith",
    "Sol Casassus Montero",
    "Soledad González Díaz",
    "Sonia Montecino Aguirre",
    "Sonia Pérez Tello",
    "Stanley Roderick Cárdenas Aravena",
    "Stefan Pszczolkowski Parraguez",
    "Stefanie Massmann Wyneken",
    "Susana Aronsohn Falickmann",
    "Susana Gazmuri Stein",
    "Svenska Arensburg",
    "Tatiana Rein",
    "Teresa Matus Sepúlveda",
    "Teresa Planet Marín",
    "Teresa Rojas Martini",
    "Teresa Vergara Ortuzar",
    "Tomás Gonzalo Arellano Salas",
    "Tomás Sepúlveda Schwember",
    "Tomas Undurraga",
    "Ulises Hernán Cárdenas Hidalgo",
    "Valentina Bulo Vargas",
    "Valentina García-Huidobro Mery",
    "Valentina Trejo Vidal",
    "Valeria Quintana Godoy",
    "Verónica Cerpa Jeria",
    "Verónica Figueroa Huencho",
    "Verónica Regina Mira Arancibia",
    "Verónica Reyes Álvarez",
    "Verónica Undurraga Schüler",
    "Vesna Puratic Hernández",
    "Vicente Espinoza",
    "Víctor Hugo de la Fuente",
    "Víctor Muñoz Tamayo",
    "Víctor Sierpe González",
    "Ximena Angélica Cuadra Montoya",
    "Ximena Orchard",
    "Ximena Rojas Retamal",
    "Ximena Tocornal Montt",
    "Ximena Valdés Subercaseaux",
    "Ximena Zabala Corradi",
    "Yanko González Cangas",
    "Yasna Doering Urrutia",
    "Yerko Araneda Martínez",
    "Yuri Carvajal Bañados",
);
$counter = 1;
//foreach( $nameArray as $name ){
//    $wpdb->query("
//        INSERT INTO wp_acciones
//        ( user_id,post_id,email,nombre ) VALUES ( 0,19502, 'firmas_$counter@firmaeqp.cl', '$name' )
//    ");
//    echo $name . "\n";
//    $counter++;
//}
//$number = $wpdb->get_var("
//        SELECT COUNT(post_id) 
//        FROM wp_acciones
//        WHERE wp_acciones.post_id = 19502
//    ");
//update_post_meta(19502, '_adhesiones', $number);
?>
